spring:
  datasource:
    url: jdbc:h2:mem:db
    username: root
    password: root
  h2.console:
    enabled: true
    path: /h2-console
    settings.web-allow-others: true

camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: Admin
  filter:
    create: All tasks

camunda.bpm.webapp.index-redirect-enabled: false

elasticsearch.clustername: science-center-app
elasticsearch.host: localhost
elasticsearch.port: 9300

storage-location: C:/papers

geocoding:
  url: https://eu1.locationiq.com/v1/search.php
  key: ${GEOCODING_ACCESS_KEY}