spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scdb?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show_sql: false
    hibernate:
      ddl-auto: update